### ISSUE TITLE
ClickUp Redirect URL

### ISSUE THREAD

**Issue by kaffimunster** [BrettBr0wn/Google-Sheets-Click-Up-API#1]
When creating the app for integration on the ClickUp side, what is used as a Redirect URL when using the API with Google Sheets? Thanks for the help!

**Comment by brettbblue** [comment]
Hey, looks like I actually forgot to use the Url variable that I set. But anyways, in the UrlFetchApp.fetch, you'll want to format your url like this: 'https://api.clickup.com/api/v1/list/list_id/task' where list_id is the id of the list you want to create a task in.

Documentation: https://clickup.com/apiv1

**Comment by kaffimunster** [comment]
Thank you so much!
